# Proxy service host. Type string.
listen_host: 0.0.0.0

# Proxy service port. Type int.
listen_port: 8080

# Mode can be "regular", "transparent", "socks5", "reverse:SPEC", or
# "upstream:SPEC". For reverse and upstream proxy modes, SPEC is host
# specification in the form of "http[s]://host[:port]". Type str.
mode: reverse:https://nunzioweb.com

# Execute a script. Type sequence of str.
scripts: ["ssdr.py"]
